// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNPYIOMOfNVNDDjpjLIgQBrxRRToiNtf4',
    appId: '1:754986498184:web:850d3e933ce17f1058873d',
    messagingSenderId: '754986498184',
    projectId: 'flutter-note-taker-1686c',
    authDomain: 'flutter-note-taker-1686c.firebaseapp.com',
    storageBucket: 'flutter-note-taker-1686c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2OwKiOJPBUqJPI7BZ8vXiUEHxZNTh6ZA',
    appId: '1:754986498184:android:50a3e212a39863df58873d',
    messagingSenderId: '754986498184',
    projectId: 'flutter-note-taker-1686c',
    storageBucket: 'flutter-note-taker-1686c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWGdqhtkndqARVjP6bWWWpksgwV17pSDU',
    appId: '1:754986498184:ios:d799fa0867e7196858873d',
    messagingSenderId: '754986498184',
    projectId: 'flutter-note-taker-1686c',
    storageBucket: 'flutter-note-taker-1686c.firebasestorage.app',
    iosBundleId: 'com.example.notetaker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWGdqhtkndqARVjP6bWWWpksgwV17pSDU',
    appId: '1:754986498184:ios:d799fa0867e7196858873d',
    messagingSenderId: '754986498184',
    projectId: 'flutter-note-taker-1686c',
    storageBucket: 'flutter-note-taker-1686c.firebasestorage.app',
    iosBundleId: 'com.example.notetaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNPYIOMOfNVNDDjpjLIgQBrxRRToiNtf4',
    appId: '1:754986498184:web:ec4849ff8190889258873d',
    messagingSenderId: '754986498184',
    projectId: 'flutter-note-taker-1686c',
    authDomain: 'flutter-note-taker-1686c.firebaseapp.com',
    storageBucket: 'flutter-note-taker-1686c.firebasestorage.app',
  );
}
